# Use official MySQL image
FROM mysql:8.0

# Set environment variables for default DB
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=bookhub
ENV MYSQL_USER=bookhub_user
ENV MYSQL_PASSWORD=bookhub_pass

# Expose MySQL port
EXPOSE 3306
